name: Building Mkdocs Page

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # run janitor on markdown input to create backlinks
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
        with:
          repository: 'hannesdelbeke/note-link-janitor'  # use fork to support subfolders
          ref: stable
          path: 'note-link-janitor'
      - name: install yarn in janitor workspace
        run: |
            cd ${{ github.workspace }}/note-link-janitor
            yarn install
            yarn run build
      - name: Run Note Link Janitor
        run: ${{ github.workspace }}/note-link-janitor/dist/index.js ${{ github.workspace }}/docs
      - name: Remove Janitor folder
        run: rm --force -r note-link-janitor
            
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force --clean
